steps:
  - name: node:14
    entrypoint: yarn
    args: ["install"]
  - name: node:14
    entrypoint: yarn
    args: ["build"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["app", "deploy", "app.yaml", "--project=shalin-dev", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY